use_frameworks!

platform :ios, '10.0'

target 'MKRemoteGateway_Example' do
  pod 'MKRemoteGateway', :path => '../'

  target 'MKRemoteGateway_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
